### ISSUE TITLE
Runtime crash on “session-persist-async”

### ISSUE THREAD

**Issue by mcritz** [hummingbird-project/hummingbird-examples#14]
When running the session-persist-async example using the provided Paw file I get "EXEC_BAD_ACCESS" at EndpointResponder.swift:29

**Comment by mcritz** [comment]
Xcode 13.0 beta 5, macOS 12 beta 21A5506j

**Comment by adam-fowler** [comment]
Do you want to try downloading latest swift from swift.org? Xcode beta 5 had an issue with continuations. See if that fixes it. Don't use Xcode RC as it has other issues.

**Comment by mcritz** [comment]
That did it! Thanks!
