### ISSUE TITLE
Request for a complete example (authentication + CURD).

### ISSUE THREAD

**Issue by DesdeChaves** [hummingbird-project/hummingbird-examples#33]
Dear Hummingbird Framework Authors,

I would like to request a complete example project dedicated to acronyms for Hummingbird, similar to the TIL (or TODOS with BEARER authentication) project in Vapor. Perhaps only in the API side. Having such an example would greatly help developers understand and explore Hummingbird's features for acronym management. 

Thank you for your support.

**Comment by adam-fowler** [comment]
Are you looking for a combination of one of the auth samples and todo samples?

**Comment by DesdeChaves** [comment]
Yes.
I'm trying hard to make the combination, but with many difficulties. I'm experimenting with the 'webauthn' example, but I'm encountering a compilation error: webauthn/Sources/App/Models/User.swift:23:17: error: cannot find type 'WebAuthnUser' in scope.

**Comment by adam-fowler** [comment]
I fixed the webauthn sample. Fixes are in PR #34

**Comment by DesdeChaves** [comment]
Great. 
Thanks a lot for your efforts. 
Can you merge all fixes? Please.

**Comment by adam-fowler** [comment]
merged. I'm also building a bigger sample which uses a number of different features

**Comment by DesdeChaves** [comment]
Thank you very much. The example already compiles without any issues, but due to my very limited knowledge, it is of little use to me. After registering with just an email ('?'), when I click on login, it tells me that the operation is insecure. 

Simpler examples, but more complete ones, are the best for less skilled people like me. A complete example would be the one that allows registration, has a login page, and can maintain the session (identifying the user_id in all database actions) when on the web and allows requests with Authorization Bearer in the API. I'll be waiting for the most comprehensive example. 

Thank you very much once again.

**Comment by adam-fowler** [comment]
You are getting the insecure operation warning because the sample is not using https.

**Comment by adam-fowler** [comment]
#35

**Comment by adam-fowler** [comment]
This is now merged

**Comment by DesdeChaves** [comment]
This example is a gem. I'll try it out and make the most of it for my projects. Thank you very much.
