### ISSUE TITLE
Access JWT data in handler

### ISSUE THREAD

**Issue by Jonovono** [hummingbird-project/hummingbird-examples#39]
I have my handler:

```
        router.group("auth")
            .add(middleware: jwtAuthenticator)
            .get("/") { req in
                return "Authenticated"
            }
```

I see I return the payload in authenticate:

```
        do {
            try signers.use(jwks: jwks)
            let payload = try signers.verify(jwtToken, as: FirebaseTokenClaims.self)
            print("Payload", payload)
            return payload
```

Is there an easy way to access certain data from this payload in my handler? Or should I use swift task local keys?

**Comment by adam-fowler** [comment]
Looking at the code for the example again, you should be able to access the `JWTPayloadData` using either
```swift
request.authGet(JWTPayloadData.self)
```
which returns an optional. 
Or
```swift
try request.authRequire(JWTPayloadData.self)
```
which throws a 401 http error if the payload data does not exist

**Comment by Jonovono** [comment]
Awesome, thanks @adam-fowler ! Will give that a try

**Comment by adam-fowler** [comment]
I should probably extend the example. To make it obvious what you need to do.

**Comment by adam-fowler** [comment]
I extended the example, but used the JWTPayloadData to convert to a User type which is supplied to the route via `authGet`
