### ISSUE TITLE
Dockerfile  build failing 

### ISSUE THREAD

**Issue by jalberty2018** [hummingbird-project/hummingbird-examples#72]
RUN cp "$(swift build --package-path /build -c release --show-bin-path)/Server" ./

Dockerfile expects "Server" as executable name

Name of compiled executable is "App"  as defined in Package.swift

targets: [
        .executableTarget(
            name: "App",

Solution : change name in Dockerfile or Package.swift

ps. change "vapor user" in "hummingbird user" in Dockerfile :-)

**Comment by adam-fowler** [comment]
Oh I forgot to update the Dockerfiles for many of the examples when merging them into one target.

**Comment by adam-fowler** [comment]
#73 should fix this. Those docker files were ancient. They referenced swift 5.3
